### ISSUE TITLE
Left pad addresses with zeros

### ISSUE THREAD

**Issue by jwasinger** [ewasm/ewasm-studio#17]
I should be able to create a contract with address 0x00...0a by entering "a" in the address field.

**Comment by hugo-dc** [comment]
When you specify an address in the address field you will call that address, not create a contract.
The requirement is to automatically pad with zeros if the address length is less than 20?

**Comment by jwasinger** [comment]
Yup.  https://github.com/ewasm/ewasm-studio/pull/24
