### ISSUE TITLE
Trying to deploy a massive contract fails with no error output

### ISSUE THREAD

**Issue by jwasinger** [ewasm/ewasm-studio#2]
Likely an issue with cpp-ethereum's RPC API.

**Comment by jwasinger** [comment]
See the blake2b example here which turns into a 64kb wasm binary:
https://github.com/jwasinger/rust-ewasm/tree/blake2b

**Comment by hugo-dc** [comment]
Got this error while trying to deploy the blake2b example: Block gas limit reached

`Error: Error: [ethjs-rpc] rpc error with payload {…dRawTransaction"} Error: Block gas limit reached."`

**Comment by jwasinger** [comment]
Yup.  We will have to preload these "precompiles" in the genesis.
